<?php

/**
 * @file
 * Provides field formatters for the GSB.
 */

/**
 * Implements hook_field_formatter_info().
 */
function gsb_field_formatter_field_formatter_info() {
  return array(
    'gsb_field_formatter_responsive_video' => array(
      'label' => t('GSB Responsive Video'),
      'field types' => array('file'),
      'settings' => array(
        'file_view_mode' => 'default',
        'preview_view_mode' => 'preview',
      ),
    ),
    'gsb_field_formatter_field_collection_separator' => array(
      'label' => t('Fields with a separator'),
      'field types' => array('field_collection'),
      'settings' =>  array(
        'view_mode' => 'full',
        'separator' => ', ',
      ),
    ),
    'gsb_field_formatter_spotlight_fid_to_image' => array(
      'label' => t('Spotlight FID to Image'),
      'field types' => array('text', 'number_integer'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function gsb_field_formatter_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'gsb_field_formatter_responsive_video':
      // Spoof the file_rendered formatter.
      $display['type'] = 'file_rendered';
      $main_element = file_entity_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display);
      foreach ($main_element as $delta => $item) {
        $element[$delta]['main'] = $item;
      }

      // Find all videos.
      $video_items = array();
      foreach ($items as $delta => $item) {
        if ($item['type'] == 'video') {
          $video_items[$delta] = $item;
        }
      }
      if ($video_items) {
        // Add a preview image for each video.
        $display['settings']['file_view_mode'] = 'preview';
        $video_element = file_entity_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $video_items, $display);
        foreach ($video_element as $delta => $item) {
          // Transform the stream wrapper into a path.
          $path = drupal_realpath($video_items[$delta]['uri']);
          // Parse the URL into parts, in order to make it an embed URL.
          $video_parts = drupal_parse_url($path);
          $embed = str_replace('watch', 'embed', $video_parts['path']) . '/' . $video_parts['query']['v'];
          // Wrap the image in a link to trigger fancybox.
          $item['wrapper'] = array(
            '#type' => 'link',
            '#title' => drupal_render($item['file']),
            '#href' => $embed,
            '#options' => array(
              'html' => TRUE,
              'query' => array(
                'autoplay' => 1,
              ),
              'attributes' => array(
                'class' => array(
                  'fancybox',
                  'fancybox.iframe',
                ),
              ),
            ),
          );
          $element[$delta]['preview'] = $item;
        }
      }
      break;

    case 'gsb_field_formatter_field_collection_separator':
      $view_mode = !empty($settings['view_mode']) ? $settings['view_mode'] : 'full';
      $count = count($items);
      foreach ($items as $delta => $item) {
        if ($field_collection = field_collection_field_get_entity($item)) {
          $element[$delta]['entity'] = $field_collection->view($view_mode);
          if ($delta != $count - 1) {
            $element[$delta]['#suffix'] = '<span class="separator">' . check_plain($display['settings']['separator']) . '</span>';
          }
        }
      }
      break;

    case 'gsb_field_formatter_spotlight_fid_to_image':
      foreach ($items as $delta => $item) {
        if ($file = file_load($item['value'])) {
          $element[$delta] = array(
            '#theme' => 'image_formatter',
            '#item' => array(
              'uri' => $file->uri,
            ),
            '#image_style' => '270x158',
          );
        }
      }
      break;
  }

  return $element;
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function gsb_field_formatter_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $element = array();

  $display = &$instance['display'][$view_mode];
  $settings = $display['settings'];
  switch ($display['type']) {
    case 'gsb_field_formatter_responsive_video':
      // Spoof the file_rendered formatter.
      $display['type'] = 'file_rendered';
      $element = file_entity_field_formatter_settings_form($field, $instance, $view_mode, $form, $form_state);
      // Add a form element for preview view mode.
      $element['preview_view_mode'] = array(
        '#title' => t('Preview view mode'),
        '#type' => 'select',
        '#options' => file_entity_view_mode_labels(),
        '#default_value' => $settings['preview_view_mode'],
      );
      break;

    case 'gsb_field_formatter_field_collection_separator':
      $entity_type = entity_get_info('field_collection_item');
      $options = array();
      foreach ($entity_type['view modes'] as $mode => $info) {
        $options[$mode] = $info['label'];
      }

      $element['view_mode'] = array(
        '#type' => 'select',
        '#title' => t('View mode'),
        '#options' => $options,
        '#default_value' => $settings['view_mode'],
        '#description' => t('Select the view mode'),
      );

      $element['separator'] = array(
        '#type' => 'textfield',
        '#title' => t('Separator'),
        '#default_value' => $settings['separator'],
        '#description' => t('Choose a separator, include any spaces'),
      );
      break;
  }

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function gsb_field_formatter_field_formatter_settings_summary($field, $instance, $view_mode) {
  $summary = '';

  $display = &$instance['display'][$view_mode];
  $settings = $display['settings'];
  switch ($display['type']) {
    case 'gsb_field_formatter_responsive_video':
      // Spoof the file_rendered formatter.
      $display['type'] = 'file_rendered';
      $summary = file_entity_field_formatter_settings_summary($field, $instance, $view_mode);
      $view_mode_label = file_entity_view_mode_label($settings['preview_view_mode'], t('Unknown'));
      $summary .= '<br>' . t('Preview view mode: %mode', array('%mode' => $view_mode_label));
      break;

    case 'gsb_field_formatter_field_collection_separator':
      $entity_type = entity_get_info('field_collection_item');
      if (!empty($entity_type['view modes'][$settings['view_mode']]['label'])) {
        $output[] =  t('View mode: @mode', array('@mode' => $entity_type['view modes'][$settings['view_mode']]['label']));
      }
      $output[] = t('Separator: "%separator"', array('%separator' => $settings['separator']));

      $summary = implode('<br>', $output);
      break;
  }

  return $summary;
}

/**
 * Implements hook_preprocess_HOOK() for file_entity.tpl.php.
 */
function gsb_field_formatter_preprocess_file_entity(&$variables) {
  // Add a class denoting the file view mode.
  $variables['classes_array'][] = 'file-' . $variables['type'] . '--' . $variables['view_mode'];
}

/**
 * Implements hook_field_group_formatter_info().
 */
function gsb_field_formatter_field_group_formatter_info() {
  return array(
    'display' => array(
      'gsb_field_formatter_group_comma_separator' => array(
        'label' => t('Comma separated'),
        'description' => t('Separate each field by a comma'),
        'format_types' => array('open'),
        'instance_settings' => array('show_label' => 1, 'label_element' => 'h3', 'classes' => ''),
        'default_formatter' => 'open',
      ),
    ),
  );
}

/**
 * #pre_render for gsb_field_formatter_group_comma_separator.
 */
function field_group_pre_render_gsb_field_formatter_group_comma_separator(&$element, $group, &$form) {
  // Sort and count all fields in this group.
  $children = element_children($element, TRUE);
  $end = count($children) - 1;
  foreach ($children as $delta => $key) {
    // Skip the last item.
    if ($delta != $end) {
      // Ensure that there is a suffix first.
      if (!isset($element[$key]['#suffix'])) {
        $element[$key]['#suffix'] = '';
      }
      // Add a comma separator.
      $element[$key]['#suffix'] .= '<span class="separator">, </span>';
    }
  }
  field_group_pre_render_div($element, $group, $form);
}
